#!/usr/bin/env sh

######################################################################
# @author      : yetist (yetist@yetipc)
# @file        : mkwineapp
# @created     : 星期五 11月 18, 2022 22:15:53 CST
#
# @description : 从.wine容器生成可安装的app目录
######################################################################

usage()
{
  echo $0 "<WINE_PREFIX_DIRECTORY>"
  exit 0
}

if [ $# -ne 1 ];then
  usage
fi

prefix_dir=`realpath $1`
name=`basename $prefix_dir`
start_dir=`mktemp -d /tmp/winapp.XXXX`
app_dir=$start_dir/$name

if [ ! -d $prefix_dir/drive_c ]; then
  exit
fi

cp -a $prefix_dir $start_dir

# USER name
sed -i "s#$USER#@current_user@#g" $app_dir/*.reg
if [ -d $app_dir/drive_c/users/$USER ]; then
    rm -f $app_dir/drive_c/users/$USER/Desktop
    rm -f $app_dir/drive_c/users/$USER/Documents
    rm -f $app_dir/drive_c/users/$USER/Downloads
    rm -f $app_dir/drive_c/users/$USER/Music
    rm -f $app_dir/drive_c/users/$USER/Pictures
    rm -f $app_dir/drive_c/users/$USER/Videos
    mv $app_dir/drive_c/users/$USER $app_dir/drive_c/users/@current_user@
fi

# Clean cache
if [ -d $app_dir/drive_c/users/$USER/AppData/Local/Microsoft/Windows/INetCache ]; then
    rm -rf $app_dir/drive_c/users/$USER/AppData/Local/Microsoft/Windows/INetCache/*
fi
if [ -d $app_dir/drive_c/users/$USER/Temp ]; then
    rm -rf $app_dir/drive_c/users/$USER/Temp/*
fi

# Clean Tencent
if [ -d $app_dir/drive_c/users/$USER/AppData/Roaming/Tencent ]; then
    rm -rf $app_dir/drive_c/users/$USER/AppData/Roaming/Tencent
fi

( cd $app_dir; tar -Jcf $start_dir/$name.tar.xz *)

cat > $start_dir/$name.metainfo << EOF
# App 名称
APP_NAME="$name"
# App 中文名称,首次启动时需要显示
APP_NAME_CN="$name"
# App 版本号
APP_VERSION="1.0"
# App 压缩包文件名
APP_ARCHIVE="$name.tar.xz"
# App 版本升级时需要忽略的文件列表
APP_IGNORE=".appignore"
# App 运行时需要进入的路径
APP_RUN_PATH="drive_c/"
# App 运行命令
APP_RUN_CMD=""
# App 运行时使用的 wine 版本号，当需要使用与默认wine不同的版本时需要指定。
APP_RUN_WINE=""
EOF

cat > $start_dir/$name.desktop << EOF
[Desktop Entry]
Name=$name
Name[zh_CN]=$name
Comment=$name
Comment[zh_CN]=$name
Exec=$name
Type=Application
StartupNotify=true
Terminal=false
Icon=$name
Categories=Game;
StartupWMClass=$name.exe
EOF

cat > $start_dir/PKGBUILD << ENDLINE
pkgname=$name
pkgver=1.0
pkgrel=1
pkgdesc="$name"
arch=('any')
url="http://www.unkonwn.com"
license=('custom')
groups=('lat')
depends=('wine')
OPTIONS=(!strip)
noextract=("\$pkgname.tar.xz")
source=("http://loongarch.zhcn.cc/sources/wine-apps/\$pkgname.tar.xz//\$pkgname.tar.xz"
    16.png
    24.png
    32.png
    48.png
    64.png
    128.png
    256.png
    \$pkgname.metainfo
    \$pkgname.desktop)
sha256sums=('SKIP')

package() {
  mkdir -p \${pkgdir}/{opt/wine-apps/\$pkgname,usr/{bin,share}}

  cat > app_ignore << EOF
user.reg
userdef.reg
system.reg
EOF
  install -Dm644 app_ignore                \${pkgdir}/opt/wine-apps/\$pkgname/.appignore
  install -Dm644 \$srcdir/\$pkgname.tar.xz   \${pkgdir}/opt/wine-apps/\$pkgname/\$pkgname.tar.xz
  install -Dm644 \$srcdir/\$pkgname.metainfo \${pkgdir}/opt/wine-apps/\$pkgname/\$pkgname.metainfo
  install -Dm644 \$srcdir/\$pkgname.desktop  \${pkgdir}/usr/share/applications/\$pkgname.desktop
  ln -sf wine-run                          \${pkgdir}/usr/bin/\$pkgname

  for i in 16 24 32 48 64 128 256; do
    if [ -f \$srcdir/\$i.png ]; then
      install -Dm644 \$srcdir/\$i.png        \${pkgdir}/usr/share/icons/hicolor/\${i}x\${i}/apps/\$pkgname.png
    fi
  done
}
ENDLINE

app_dir="/tmp/winapp.${pkgname}"
mv $start_dir $app_dir

echo "The app develop files is $app_dir"
